In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

In [35]:
df = pd.read_csv('car.csv')

In [36]:
dummy = pd.get_dummies(df['Car Model'])
merge = pd.concat([df,dummy], axis = 'columns')

In [37]:
final = merge.drop(['Car Model','Mercedez'], axis = 'columns')

In [70]:
x = final.drop('Sell Price($)', axis = 'columns').values
y = final.iloc[:,1]
x

array([[69000,     6,     0,     1],
       [35000,     3,     0,     1],
       [57000,     5,     0,     1],
       [22500,     2,     0,     1],
       [46000,     4,     0,     1],
       [59000,     5,     1,     0],
       [52000,     5,     1,     0],
       [72000,     6,     1,     0],
       [91000,     8,     1,     0],
       [67000,     6,     0,     0],
       [83000,     7,     0,     0],
       [79000,     7,     0,     0],
       [59000,     5,     0,     0]], dtype=int64)

In [71]:
reg = LinearRegression()
reg.fit(x,y)
reg.score(x,y)
reg.predict([[86000,7,0,1]])

array([11080.74313219])

In [62]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0     BMW X5    69000          18000         6
1     BMW X5    35000          34000         3
2     BMW X5    57000          26100         5
3     BMW X5    22500          40000         2
4     BMW X5    46000          31500         4
5    Audi A5    59000          29400         5
6    Audi A5    52000          32000         5
7    Audi A5    72000          19300         6
8    Audi A5    91000          12000         8
9   Mercedez    67000          22000         6
10  Mercedez    83000          20000         7
11  Mercedez    79000          21000         7
12  Mercedez    59000          33000         5

In [68]:
# using one hot encoding
i = df.drop('Sell Price($)', axis = 'columns').values
o = df['Sell Price($)'].values
pre = make_column_transformer((OneHotEncoder(), [0]), remainder = 'passthrough')
var = pre.fit_transform(i)
fi = var[:,1:]
reg.fit(fi,o)
reg.score(fi,o)
fi

array([[1.0, 0.0, 69000, 6],
       [1.0, 0.0, 35000, 3],
       [1.0, 0.0, 57000, 5],
       [1.0, 0.0, 22500, 2],
       [1.0, 0.0, 46000, 4],
       [0.0, 0.0, 59000, 5],
       [0.0, 0.0, 52000, 5],
       [0.0, 0.0, 72000, 6],
       [0.0, 0.0, 91000, 8],
       [0.0, 1.0, 67000, 6],
       [0.0, 1.0, 83000, 7],
       [0.0, 1.0, 79000, 7],
       [0.0, 1.0, 59000, 5]], dtype=object)

In [69]:
reg.predict([[1,0,86000,7]])

array([11080.74313219])